---

charts:
  - name: qubership-mistral-operator
    chart_file: operator/deployments/charts/mistral-operator/Chart.yaml
    values_file: operator/deployments/charts/mistral-operator/values.yaml
    image:
      - ghcr.io/netcracker/qubership-mistral-operator-img:${release}
      - ghcr.io/netcracker/qubership-mistral-operator-bluegreen-agent-img:${release}
      - ghcr.io/netcracker/qubership-mistral-operator-transfer-img:${release}
      - ghcr.io/netcracker/qubership-mistral:${release}
      - ghcr.io/netcracker/qubership-mistral-tests:${release}
      - ghcr.io/netcracker/qubership-disaster-recovery-daemon:v0.4.5
