apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mistral-secret
  labels:
    app.kubernetes.io/part-of: {{ default "mistral" .Values.kubernetesLabels.mistralOperator.partOf }}
    app.kubernetes.io/managed-by: {{ default "Helm" .Values.kubernetesLabels.mistralOperator.managedBy }}
    deployment.netcracker.com/session-id: "{{ .Values.DEPLOYMENT_SESSION_ID }}"
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
data:
  {{- include "idpSecrets.populate" . | nindent 2 }}
  idp-user-robot: {{ .Values.secrets.idpUserRobot | b64enc }}
  idp-password-robot: {{ .Values.secrets.idpPasswordRobot | b64enc }}
  idp-registration-token: {{ .Values.secrets.idpRegistrationToken | b64enc }}
  pg-admin-password: {{ (include "mistral.pgAdminPass" .) | b64enc }}
  pg-admin-user: {{ (include "mistral.pgAdminUser" .) | b64enc }}
  pg-password: {{ (include "mistral.pgPass" .) | b64enc }}
  pg-user: {{ (include "mistral.pgUser" .) | b64enc }}
  kafka-sasl-plain-username: {{ (include "mistral.kafkaAdminUsername" .) | b64enc }}
  kafka-sasl-plain-password: {{ (include "mistral.kafkaAdminPassword" .) | b64enc }}
  rabbit-admin-password: {{ (include "mistral.rabbitAdminPassword" .) | b64enc }}
  rabbit-admin-user: {{ (include "mistral.rabbitAdminUser" .) | b64enc }}
  {{- if .Values.mistralLite.includeLocalRmq }}
  rabbit-password: {{ .Values.secrets.rabbitAdminPassword | b64enc }}
  rabbit-user: {{ .Values.secrets.rabbitAdminUser | b64enc }}
  {{- else }}
  rabbit-password: {{ .Values.secrets.rabbitPassword | b64enc }}
  rabbit-user: {{ .Values.secrets.rabbitUser | b64enc }}
  {{- end }}
{{- if .Values.mistralLite.includeLocalRmq }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: rabbitmq-default-secret
data:
  rmqcookie: 'c2VjcmV0Y29va2ll'
  password: {{ .Values.secrets.rabbitAdminPassword | b64enc }}
  user: {{ .Values.secrets.rabbitAdminPassword | b64enc }}
{{- end }}
