apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mistralservices.netcracker.com
spec:
  scope: Namespaced
  group: netcracker.com
  version: v1
  names:
    kind: MistralService
    plural: mistralservices
    singular: mistralservice
    shortNames:
      - mistral
      - mistrals
